### PR TITLE
Combine `getXSTSToken` & `getXSTSTokenWithTitle` and implement own `getUserToken` 

### PR DESCRIPTION
**Pull request by LucienHH**

### CODE REVIEW

**Comment by LucienHH** [comment]
Cc @extremeheat

**Comment by extremeheat** [comment]
Have you tested to work?

**Comment by LucienHH** [comment]
Yeah tested ok, manual tests ran fine as well.

**Review by extremeheat — APPROVED** [review]

**Comment by extremeheat** [comment]
Thanks! I think we can incrementally release this/other PRs to avoid potentially breaking things in one big release, auth can be tricky to hunt down problems in

**Pull request merged**
