### PR TITLE
Update LiveTokenManager.js

### PR DESCRIPTION
**Pull request by kairu82642**
Now you can log in just by jumping to the page

### CODE REVIEW

**Comment by extremeheat** [comment]
How do you know this works?

**Comment by kairu82642** [comment]
> How do you know this works?
I'm Japanese and actually own SWITCH.I found out about this because when I read the QR code, this query came up.
2023111216083200-11B64E28AD7A49CA9EC8AC007BE858C6
PXL_20231112_070824378

**Comment by extremeheat** [comment]
Ok, when I go to

https://microsoft.com/link?otc=T3ZJR8RD

I get redirected to a blank page. image

Maybe this only works in some areas?

**Comment by SilkePilon** [comment]
> Ok, when I go to
> 
> https://microsoft.com/link?otc=T3ZJR8RD
> 
> I get redirected to a blank page.
> 
> Maybe this only works in some areas?

Same for me. Im also getting redirected to a blank page.

**Comment by w0ahL** [comment]
> Ok, when I go to
> 
> https://microsoft.com/link?otc=T3ZJR8RD
> 
> I get redirected to a blank page. image
> 
> Maybe this only works in some areas?

This works perfectly fine for me, but I am using a Azure Application App, but I don't know if that makes any difference or not.

**Comment by extremeheat** [comment]
The LiveTokenManager.js that you're modifying is for non-Azure apps (only works for official Minecraft client IDs). If you use an Azure app, MsaAuthFlow (using official msal lib) is used instead. The message for MsaAuthFlow is provided by the server, and we don't modify or manually specify it like in LiveTokenManager.

Anyway when I scan your QR code the input box is still empty, though I do get the "?otc" part in the URL. There might be a geographic difference in the login page code.

**Comment by LucienHH** [comment]
@extremeheat This only works for valid codes, the codes shared by the others here have likely been used or expired hence why they don't work and redirect to the main page. I've just tested on a fresh code gen and is working fine. Very useful to be honest!

**Comment by extremeheat** [comment]
Yeah, I see. It doesn't work on my phone but does work seem to work on my computer. But only for microsoft.com/link, not at https://microsoft.com/devicelogin endpoint (which LiveTokenManager doesn't use). It's also not documented (I don't see anything in microsoft docs), so I'd suggest adding this link at the end of the current prompt, explicitly using https://microsoft.com/link?otc=....

Perhaps like `To sign in, use a web browser to open the page $url and use the code $code or visit http://microsoft.com/link?okx=$code`

**Comment by kairu82642** [comment]
https://github.com/PrismarineJS/prismarine-auth/assets/149259428/44d48aa6-384b-41d9-8fff-8f1728452f14

**Comment by extremeheat** [comment]
Yes, I understand. I was just commenting that we should have both the code separate and embedded into the URL. This way we don't have problems if people go to the link and it's not prefilled and it's not obvious the query string parameter is the code to type in. I've updated the text in the PR to do this.

**Comment by kairu82642** [comment]
@extremeheat 
I would like to see this feature added to prismarine-auth!

**Comment by extremeheat** [comment]
Sorry for the delay. LGTM, thanks for the investigation on this :)

**Pull request merged**
