### PR TITLE
Let devs log the code callback if they want & Some typings for Device Code

### PR DESCRIPTION
**Pull request by ATXLtheAxolotl**
-Type for code callback, probably should make a type at the bottom or something instead of a object shoved up there but it will work
~- Added authCallback, I plan on using this for bedrock-protocol later because as I recall there isn't an existing method to detect when they've logged in just the codeCallback and I need to know after they sign-in for a project.~
-Returns when there is a codeCallback before it logs to console, if people need it logged and need codeCallback at the same time they can log it to console themselves.

### CODE REVIEW

**Comment by extremeheat** [comment]
There is no need for the ”auth callback”, the function already returns a promise with the token data on completion

**Comment by ATXLtheAxolotl** [comment]
> There is no need for the ”auth callback”, the function already returns a promise with the token data on completion

Oh it does? How would I detect this completion in bedrock-protocol?

**Comment by extremeheat** [comment]
You listen for one of the many events emitted after login there, see the docs

**Comment by ATXLtheAxolotl** [comment]
I've removed the authCallback

**Review by extremeheat — APPROVED** [review]

**Comment by extremeheat** [comment]
Thanks

**Pull request merged**
