### PR TITLE
Replace mocha with Jest

### PR DESCRIPTION
**Pull request by hornta**
I saw something about jest not working in prismarine-auth and I've been meaning to contribute code wise to prismarine

### CODE REVIEW

**Comment by rom1504** [comment]
looks like you reproduced the issue
good luck on fixing it :)

**Comment by hornta** [comment]
> looks like you reproduced the issue
> good luck on fixing it :)
weird because it works flawlessy in node 16. Must be smth with node 14

**Comment by hornta** [comment]
I raised an issue in the Jest repo about this error so this PR is blocked by it. https://github.com/facebook/jest/issues/11754

**Comment by rom1504** [comment]
@hornta how can we work around this ?
I don't think they will solve this in a timely manner

**Comment by hornta** [comment]
@rom1504 We could go back to an older version of Jest but I'm not sure that is a viable option. Alternatively we can use https://www.npmjs.com/package/patch-package to modify the jest package upon installation.

**Comment by rom1504** [comment]
that doesn't work. We need to make this package work for dependent packages that use jest. We do not control the version of jest used there

**Comment by rom1504** [comment]
is there something that we can do here to make it work with the last jest version without touching jest or its config ?

**Comment by extremeheat** [comment]
Please see #10, I already made an issue there which is confirmed https://github.com/facebook/jest/issues/9771. This is an issue with jest using their own require function which doesn't support the export field properly. The suggested workaround is a patch, https://github.com/facebook/jest/issues/9771#issuecomment-841624042 but I don't think this is sustainable. 

More information on this can be found in this conversation - https://discord.com/channels/413438066984747026/600013790913757244/842987948579356682.

The creator of node-jose is also a node.js developer who has implemented the changes into node 16. So the workaround for node 16 is not necessary, this dep was added specifically so older node versions (i.e. 14) work.

**Comment by rom1504** [comment]
any of this doesn't sound like it will be solved in the coming weeks.
what can we do on our side in this package to make it work ? (for example change something in a jose fork ?)

**Comment by hornta** [comment]
We could try and not use the crypto algorithm from node and instead use https://www.npmjs.com/package/js-crypto-ec or similar packages.
@extremeheat It has nothing to do with Jest not working? I can reproduce this without the jose package. I think I'm missing a bit of history

**Comment by extremeheat** [comment]
If you know what you're doing, you can try it. This is an instance of the library already holding a public key, which then needs to be transformed to a JWK. You can see the issue in jest for more info on that.

**Comment by extremeheat** [comment]
I looked at your issue on jest, it's unrelated to the issue here. Your call to `generateKeyPairSync` is a sync function (there's also an async version) that will block the process so I guess jest is hanging on that. But not related to the issue we have here. 

So anyway short-term solution wise, I think it comes down to these options:
* port the transform code over to pauth
* fork `jose`, remove export field and do a custom npm release
* require node 16
* use the jest workaround
* don't use node crypto, use alternative lib (if you want to do this, you will also have to update the accompanying signature/singing code)

**Comment by rom1504** [comment]
I think these 2 options are worth considering:
* fork jose, remove export field and do a custom npm release
* require node 16

do you want to try the first option @hornta ? if it doesn't work / is too annoying, we can consider going to node 16
node 14 will reach maintenance status in a few months

**Comment by hornta** [comment]
> I looked at your issue on jest, it's unrelated to the issue here. Your call to `generateKeyPairSync` is a sync function (there's also an async version) that will block the process so I guess jest is hanging on that. But not related to the issue we have here.
> 
> So anyway short-term solution wise, I think it comes down to these options:
> 
> * port the transform code over to pauth
> * fork `jose`, remove export field and do a custom npm release
> * require node 16
> * use the jest workaround
> * don't use node crypto, use alternative lib (if you want to do this, you will also have to update the accompanying signature/singing code)

I tested using the async version as well but it's the same.

I try using this package `js-crypto-ec` but I'm not sure if it can work because it doesn't look like it supports the IEEE P1363 signature type and instead I used the ASN.1 / der. I don't know how to test this since I know nothing about xbox or bedrock for that matter so I can take some help there.

**Comment by extremeheat** [comment]
You need to make sure `authTitle` is set. This should always be set or the signing is skipped. Signing is needed to properly do the full auth (I think we should do an assert to ensure this is set). For testing, do

```js
    const { Authflow, Titles } = require('prismarine-auth')
    const flow = new Authflow('username', './', { authTitle: Titles.MinecraftJava }, onMsaCode)
    flow.getXboxToken()
    flow.getMinecraftJavaToken()
```

Doing a call to `getMinecraftBedrockToken` requires a separate keypair.

```js
const { Authflow } = require('prismarine-auth')
const crypto = require('crypto')
const curve = 'secp384r1'

if (process.argv.length !== 4) {
  console.log('Usage: node deviceCode.js <username> <cacheDirectory>')
  process.exit(1)
}

const keypair = crypto.generateKeyPairSync('ec', { namedCurve: curve }).toString('base64')
const doAuth = async () => {
  const flow = new Authflow(process.argv[2], process.argv[3], { authTitle: Titles.MinecraftNintendoSwitch })
  const token = await flow.getMinecraftBedrockToken(keypair)
  console.log(token)
}
```

**Comment by hornta** [comment]
Mocked both the xbox-live and azure package in tests for the purpose of making it easier and possible to test different cases and also to make them less flaky in case. This is done using Jest https://jestjs.io/docs/manual-mocks#mocking-node-modules

I also added https://mswjs.io/ which is a great tool for mocking requests which lets you also handle special edge cases and also to make the tests less flaky.

**Comment by extremeheat** [comment]
The test mocking is cool, yeah. But I'm not sure it's solving any problem we have right now? Have you tested to make sure all the exposed API still work (getXbox, minecraftJava and minecraftBedrock tokens)? This approach will need to be paired with changes in bedrock-protocol otherwise this is a breaking change.

**Comment by extremeheat** [comment]
Switching the signing algorithm will definitely break things I think. As for the documentation, there isn’t any :). The current codebase (and 1 or 2 others) are the only implementations I know of. So if you really want to not use native crypto, aside from degraded performance it’s probably going to be a challenge.

**Comment by hornta** [comment]
The mocking was necessary since a lot of the tests were still actually running after asserting e.g. promises was not await-ed for so output was still sent to console and Jest doesn't like that(for good reasons). I h ave not changed any public APIs but we can make further tests to ensure the public methods are accessible.

I don't think I can test this because wouldn't that mean I need to own a bedrock account or an xbox/microsoft account for signing in? I hope can I get some testing help from people who owns these types of accounts. It should just be a matter of "checking if it still works" right, or is there more to it? 

I would love to use node native crypto if not Jest were complaining about generating keys.

**Comment by hornta** [comment]
can I trigger a recheck because the failed tests are failing on outdated code somehow...

**Comment by rom1504** [comment]
@u9g @extremeheat could anyone check if this work in bedrock-protocol ?

**Comment by extremeheat** [comment]
This changes a lot of things with crypto which I'm not so sure about and would need changes in bedrock-protocol to use this crypto lib also (the process is already pretty fragile). 

I tried this PR and through gitpod when calling getMinecraftBedrockToken I get a 403.

**Comment by rom1504** [comment]
this is now unneeded, jose and jest work together

**Pull request closed without merging**
