### PR TITLE
Update mcs entitlements endpoint

### PR DESCRIPTION
**Pull request by frej4189**
Fixes https://github.com/PrismarineJS/node-minecraft-protocol/issues/1295

Also related (these issues were closed despite not being resolved?):

- https://github.com/PrismarineJS/mineflayer/issues/3286
- https://github.com/PrismarineJS/mineflayer/issues/2890

### CODE REVIEW

**Comment by frej4189** [comment]
Tests failing. Not entirely sure how this test suite could ever succeed?

**Comment by LucienHH** [comment]
Test are failing due to the default clientId: https://github.com/PrismarineJS/prismarine-auth/blob/fcc959b6e9439e4d43dfadbcc2b95d2d9a6042f9/src/common/Constants.js#L27

No longer being a valid client thus causing the test for fetching deviceCode to fail.

Honestly I'm not sure of the benefit of keeping `msal` as our default flow, we might as well default to `live` and set authTitle to Minecraft Nintendo. `msal` is only really needed if using a custom azure app.

**Comment by extremeheat** [comment]
Yeah, it can be changed to default to `live`. Although we have to default to a Minecraft bedrock token which may not be appropriate for all users, more importantly we want to keep auth API working without breaking auth workflows for downstream users. Will be done with #97

**Comment by extremeheat** [comment]
Can you rebase on master?

**Comment by frej4189** [comment]
Rebased

**Review by extremeheat — APPROVED** [review]
Would be great to know when this changed. Can anyone test to make sure it works?

**Comment by frej4189** [comment]
> Would be great to know when this changed. Can anyone test to make sure it works?

We run with this endpoint at https://minecraftafk.com (managing thousands of accounts). We have no reported auth issues since making the update.

**Review by extremeheat — CHANGES_REQUESTED** [review]
I just tested against both present master and your PR, and they both are working which is a bit odd. They do not return the same data so this could be a breaking change, what do we do about that and do you know why one endpoint would work and not the other?

**Comment by extremeheat** [comment]
From a quick check of node-minecraft-protocol we also don't actually verify anything inside `entitlements`, but only use it for logging debug information. Assuming nothing else big is using it I think we can make this change with a note in the API changelog without breaking anything.

The linked issues PrismarineJS/mineflayer#3286 and PrismarineJS/mineflayer#2890 have to do with the /profile endpoint so any changes to the Minecraft java entitlements endpoint here would be unrelated to them. Do you think the PR is still separately valid?

**Comment by frej4189** [comment]
> The linked issues PrismarineJS/mineflayer#3286 and PrismarineJS/mineflayer#2890 have to do with the /profile endpoint so any changes to the Minecraft java entitlements endpoint here would be unrelated to them. Do you think the PR is still separately valid?

That's a reasonable assumption but actually incorrect. When refreshing tokens for Xbox Game Pass accounts (and likely other newer accounts) without fetching entitlements, the profile endpoint will return no data. As soon as you make the entitlements request, the profile endpoint is populated. Mojang at their best.

**Comment by frej4189** [comment]
> They do not return the same data so this could be a breaking change, what do we do about that and do you know why one endpoint would work and not the other?

I guess the old endpoint is preserved for backwards compatibility (why?). As (kind of) mentioned above the current endpoint only seems to cause issues when trying to _refresh_ the token of a newer account (my assumption is post-migration).

**Comment by extremeheat** [comment]
Can you update the types?

**Pull request closed without merging**
