### PR TITLE
Allow getting all tokens

### PR DESCRIPTION
**Pull request by sdFSDFSADF**
rewrite of getMsaTokens() but returns full ret instead

useful for those who want everything

lmk if docs need to be written too its pretty much the same as getMsaToken()

### CODE REVIEW

**Comment by sdFSDFSADF** [comment]
when testing it returns 
`{
  accessToken: '...'
}
`

still testing

**Comment by sdFSDFSADF** [comment]
fixed. removed cache from function due to the functions nature and use

**Comment by sdFSDFSADF** [comment]
never mind, still returning just accesstoken. looking into livetokenmanager.js

**Comment by sdFSDFSADF** [comment]
should be fully fixed

**Comment by extremeheat** [comment]
First, per the [don't repeat yourself principle](https://en.wikipedia.org/wiki/Don't_repeat_yourself), it's best in code to not repeat large pieces of code when adding new functionality. What you should be doing is adding abstraction. In this case, via updating (and renaming) the current function to expand the data it returns, then adding a new function in the same name as the old one that calls the lower function and returns what's expected by the current API.

Since the TokenManager/* files are internal, it's ok to ignore compatibility there, so the existing code can be changed as needed.

Also, returning arbitrary data from a server is not good. This would need to be added to the doc yes, along with explicitly what data we're providing. As we have to keep that stable if it changes.

**Comment by rom1504** [comment]
ci is failing

**Comment by rom1504** [comment]
please re open if you want to finish it

**Pull request closed without merging**
