### PR TITLE
Bun compatibility layer for XboxTokenManager

### PR DESCRIPTION
**Pull request by GustavoWidman**
Should fix the compatibility issue when running with bun caused by some cryptography object inconsistencies.

### CODE REVIEW

**Comment by GustavoWidman** [comment]
For some reason these tests are failing even with the repo clean. WTF?

**Comment by extremeheat** [comment]
Hello, can you please explain what is being changed here and why?

Is there a bug in a library, our code or on the side of Bun? From the sounds of it this appears to be a bug in Bun. Can this not be fixed upstream, where it seems more appropriate?

**Comment by GustavoWidman** [comment]
> Hello, can you please explain what is being changed here and why?
> 
> Is there a bug in a library, our code or on the side of Bun? From the sounds of it this appears to be a bug in Bun. Can this not be fixed upstream, where it seems more appropriate?

While this is a bug on Bun's side, currently Bun has not showed any intent on fixing this. This small commit works around the incompatibility and makes sure the library runs as expected in both runtimes.

**Comment by extremeheat** [comment]
Is there a relevant issue in Bun for it yet? I assume all users of jose would have similar problems. This specific code was last modified by maintainer of jose.

**Comment by extremeheat** [comment]
Was fixed by #103

**Pull request closed without merging**
